### ISSUE TITLE
Discussion thread

### ISSUE THREAD

**Issue by matsui528** [missing-semester-jp/missing-semester-jp.github.io#16]
@denkiwakame @ikuehirata @kshibayama @logcpp @makotoshimazu @soramichi @Katsumata210 @translucens @take1108 

用語の統一についての議論や、質問がある場合のために、このissueを立てました。自由に使ってください。

**Comment by soramichi** [comment]
マージの手順・基準ってどうなってますか？翻訳されたものを organizer が読んで確認、という感じでしょうか。

**Comment by ikuehirata** [comment]
用語について質問です。門外漢なので適切な用語をご教示ください。
1 symlinkの一般的な日本語は？ ソフトリンク？ シンボリックリンク？
2 portability（dotfileを複数のマシンで適用して、どこでも同じようにshell等の設定を同じに維持できる意味）の日本語は？ 可搬性？ 移植性？

**Comment by matsui528** [comment]
> マージの手順・基準ってどうなってますか？翻訳されたものを organizer が読んで確認、という感じでしょうか。

そうですね。完成したらPRを作ってもらい、とりあえずマージしようと思います。翻訳内容については、確認というほどの確認もしないです。全章の翻訳をざっと完了させることをまず目標にします。マークダウンのレンダリングがおかしくなっていないかとか、翻訳し忘れている個所がないかどうかはオーガナイザーで確認します。

**Comment by matsui528** [comment]
> 1 symlinkの一般的な日本語は？ ソフトリンク？ シンボリックリンク？

シンボリックリンクでしょうか。

> 2 portability（dotfileを複数のマシンで適用して、どこでも同じようにshell等の設定を同じに維持できる意味）の日本語は？ 可搬性？ 移植性？

「移植性」にしますか・・？「軽量である」というニュアンスがあるような気がしますが。。。

上記二点、他にご意見のある方がいらしたらお願いします。

**Comment by matsui528** [comment]
（翻訳者の方の追加：　@tomo-makes 　このスレッドに気付いていただくためにメンションしています）

**Comment by makotoshimazu** [comment]
> 2 portability（dotfileを複数のマシンで適用して、どこでも同じようにshell等の設定を同じに維持できる意味）の日本語は？ 可搬性？ 移植性？

Portabilityの訳語としては、可搬性、移植性、携帯性などがありそうですが、とくにソフトウェアの文脈では前の２つ（可搬性・移植性）が用いられているように思います。
どちらでも良さそうに思えますが、[移植性](https://www.google.com/search?q=%E7%A7%BB%E6%A4%8D%E6%80%A7)のほうが[可搬性](https://www.google.com/search?q=%E5%8F%AF%E6%90%AC%E6%80%A7)より検索のヒット数が多いので一般的なのかもしれないです。（個人的には可搬性のほうが書籍ではよく見かけるイメージがあったので若干意外でした。）

**Comment by makotoshimazu** [comment]
> マージの手順・基準ってどうなってますか？翻訳されたものを organizer が読んで確認、という感じでしょうか。

PRをレビューしてよいタイミングで、 @matsui528 , @makotoshimazu , @take1108 のいずれかをPRのレビュワーに追加していただけると助かります。

**Comment by kshibayama** [comment]
Portabilityの訳出について、英英辞典を見てみました。[一般的な語義](https://www.oxfordlearnersdictionaries.com/definition/english/portability)からすると可搬性や運搬容易性などと表現できそうですが、[CS的語義](https://www.oxfordlearnersdictionaries.com/definition/english/portable_1)からすると移植性や移植容易性のほうが読者にイメージを掴んでもらいやすいかもしれません。個人的には easy の意味を明確にするために`〜容易性`とするほうが好きですが、慣習を重んじるべき向きもあるかもしれないので判断はお任せします。（[Cambridge DictionaryでもIT/Comm用語として記載がありますが](https://dictionary.cambridge.org/dictionary/english/portable)、翻訳の助けという観点では少し遠回りな表現と感じました。）

**Comment by ikuehirata** [comment]
訳出について、皆さまありがとうございます。今のところsymlinkはシンボリックリンク、portabilityは移植性としておきますが、他にもご意見があればどうぞご教示ください。

**Comment by matsui528** [comment]
@ikuehirata さんに早速一つ目を仕上げていただきました 🎉 有難うございます！

https://missing-semester-jp.github.io/2020/command-line/

**Comment by soramichi** [comment]
外部リンクはひとまず原文と同じものを使っていますが、可能な限り日本語版に置き換えたほうがよいでしょうか？

**Comment by matsui528** [comment]
基本、原文と同じリンクにしましょうか。日本語版で有益なページがある場合、オプションとして、「訳注：日本語版リンク」のようにつけてもよい、としますか。

**Comment by matsui528** [comment]
@soramichi さんにメタプログラミングを仕上げていただきました 🎉 

https://missing-semester-jp.github.io/2020/metaprogramming/

**Comment by matsui528** [comment]
@logcpp さんにシェルツールを翻訳していただきました 🎉 

https://missing-semester-jp.github.io/2020/shell-tools/

**Comment by ikuehirata** [comment]
vimのmodifierの訳出に関して質問です。modifierの単語が出てくる editors.md と potpourri.md を担当している方にメンションを飛ばしています。@denkiwakame @take1108
暫定的に「修飾子」としましたが、既に他の単語で訳した、またはお好みはありますか？

**Comment by denkiwakame** [comment]
@ikuehirata 
-  `editors.md` での `modifier` は Vim用語でいう `motion` `=missing-semester ではnoun` に対する**修飾子**，
  - https://github.com/vim/vim/blob/master/runtime/doc/change.txt#L45-L46
-  `potpourri.md` での `modifier` は キーマッピングの文脈での **修飾キー** 
- ではないかと思います. どちらも Vim固有の用語としての modifier ではないため，統一はしなくても良いのかなと思いました.
- `editors.md` は元々の本文自体が vimの用語と少しずれているのが気になっていて，vimdoc の方がわかりやすいかもしれません  https://github.com/vim/vim/blob/master/runtime/doc/intro.txt

**Comment by matsui528** [comment]
再び @ikuehirata さんに、講義ノートを翻訳していただきました 🎉 

https://github.com/missing-semester-jp/missing-semester-jp.github.io/blob/master/_2020/editors-notes.txt

**Comment by ikuehirata** [comment]
> @ikuehirata
> 
> * `editors.md` での `modifier` は Vim用語でいう `motion` `=missing-semester ではnoun` に対する**修飾子**,
> * https://github.com/vim/vim/blob/master/runtime/doc/change.txt#L45-L46
> * `potpourri.md` での `modifier` は キーマッピングの文脈での **修飾キー**
> * ではないかと思います. どちらも Vim固有の用語としての modifier ではないため,統一はしなくても良いのかなと思いました.
> * `editors.md` は元々の本文自体が vimの用語と少しずれているのが気になっていて,vimdoc の方がわかりやすいかもしれません  https://github.com/vim/vim/blob/master/runtime/doc/intro.txt

詳細にありがとうございます。editors-notes.txt では「修飾子」で統一しますが、ご指摘の通り他ファイルではそれぞれ適切な訳出でお願いいたします。

**Comment by matsui528** [comment]
@makotoshimazu によるデバッグとプロファイリングが完了しました 🎉 

https://missing-semester-jp.github.io/2020/debugging-profiling/

**Comment by matsui528** [comment]
@take1108 に「雑録」を翻訳してもらいました 🎉 

https://missing-semester-jp.github.io/2020/potpourri/

**Comment by matsui528** [comment]
現在翻訳中の皆様、
ハードな締め切りを設ける気は全くないのですが、もし３月中に翻訳を完了していただけると、４月頭に「このmissing semester邦訳版を読んでおくといいよ」とラボ/職場の新人に宣伝できるので、良さそうです。

**Comment by matsui528** [comment]
再び再び @ikuehirata さん（プロ翻訳家でもあります）に「Q&A」を翻訳していただきました。有難うございます！:tada:

https://missing-semester-jp.github.io/2020/qa/

**Comment by matsui528** [comment]
@translucens さんに「セキュリティと暗号」を翻訳していただきました！ 🎉 

https://missing-semester-jp.github.io/2020/security/

**Comment by matsui528** [comment]
@Katsumata210 さんに「バージョン管理 (Git)」を翻訳していただきました 🎉 

https://missing-semester-jp.github.io/2020/version-control/

**Comment by matsui528** [comment]
@denkiwakame さんに「エディタ (Vim)」を翻訳していただきました :tada:

https://missing-semester-jp.github.io/2020/editors/

**Comment by matsui528** [comment]
@kshibayama さんに「講座概要 + シェル」を翻訳していただきました :tada:

https://missing-semester-jp.github.io/2020/course-shell/

**Comment by matsui528** [comment]
@tomo-makes さんに「データラングリング」を翻訳していただきました :tada:

https://missing-semester-jp.github.io/2020/data-wrangling/

**Comment by matsui528** [comment]
これにて全章の翻訳が完了したため、このissueは閉じます。もし何かまた議論すべき点が出てきたら、再度オープンしてください。有難うございました！

**Comment by matsui528** [comment]
自分が書いた部分に関するPRが来た場合、自分の権限でレビュー・マージしていただいて大丈夫です。

**Comment by matsui528** [comment]
というか、書いていただいた方をレビュアにアサインする方向でいきましょうか。私か @take1108 か @makotoshimazu がPRに担当者をアサインすることにしましょう。（アサインされる前にPRに気付いたら、レビューを始めちゃって大丈夫です）
