### ISSUE TITLE
_斜体_ が日本語だとうまく斜体にならない

### ISSUE THREAD

**Issue by makotoshimazu** [missing-semester-jp/missing-semester-jp.github.io#18]
`_斜体_` という記法が、日本語の場合だと手元の環境（windows, chrome）では斜体にならないことに気づきました。
下記にテスト用のテキストを貼っておきます。僕の環境ではGitHubでも日本語は斜体になりません。

- 日本語：_斜体_
- 英語：_italic_

ひとまず `_斜体_` という記法は維持したまま翻訳しますが、見た目上なにかしら変化があったほうが良いかと考えています。
いまのところ思いついた解決法は以下です。

* 斜体になるWebフォントを導入する
* 日本語において `_斜体_` ではなく別の表記法（たとえば `__太字__`）を利用する

他にもなにかアイデア・意見があれば教えていただけると嬉しいです。

**Comment by makotoshimazu** [comment]
@matsui528 @take1108 一応メンション飛ばしておきますね

**Comment by soramichi** [comment]
Windows/Linux, Chrome/Firefox の組み合わせで試したところ Windows + Chrome のみ斜体になりませんでした。

昔組版に詳しい人に聞いた話なのですが、そもそも日本語で斜体は使うべきでないというのが組版業界（？）でよくある意見のようです。
http://www.creators-station.jp/report/103138
http://www.kt.rim.or.jp/~tyamamot/aboutitalicsinJapanese.html

**Comment by matsui528** [comment]
なるほど。windows + edgeでもダメですね（chromiumベースなのでchromeと同じですね）　マックは持ってないので試してないですが、iphoneのサファリだと大丈夫のようです。linux + chromeでうまくいくのは面白い（？）ですね

とりあえずあまりルールを設けず愚直に訳すほうがよいと思うので、「ひとまず斜体記法は維持したまま翻訳」にしましょう。

斜体も綺麗にレンダリングしてくれるようなwebフォントがあり、かつ簡単に導入できるなら検討してみてもよさそうですね。太字にしてしまうのはマズそうな気がします（原文で太字と斜体を使い分けている箇所があるかもしれないので）

**Comment by ikuehirata** [comment]
> 太字にしてしまうのはマズそうな気がします(原文で太字と斜体を使い分けている箇所があるかもしれないので)

太字と斜体の使い分けがされている箇所に遭遇しましたので、ご報告をば。https://missing-semester-jp.github.io/2020/command-line/ のターミナルマルチプレクサ、ドットファイルの箇条書きのところ、「シンボリックリンク」の強調等に使われています

**Comment by makotoshimazu** [comment]
Noto Sans JPをつかうことで表示できるようになったのでcloseします。
