### ISSUE TITLE
tracking id の削除

### ISSUE THREAD

**Issue by soramichi** [missing-semester-jp/missing-semester-jp.github.io#20]
config.yml の以下の行に Google Analytics らしき tracking id が入っていますが、これは原文のページの作者が原文のページへのアクセスを収集するためにつけているものなので翻訳版では削除するべきではないでしょうか。

https://github.com/missing-semester-jp/missing-semester-jp.github.io/blob/fa309f93162654a5a4993df8b151a1efc26ceb5c/_config.yml#L16

**Comment by matsui528** [comment]
ありがとうございます！はい、削除すべきだと思います。削除PRを作っていただけないでしょうか？

cc: @makotoshimazu @take1108 何か問題があれば言ってください
